### ISSUE TITLE
just 4task

### ISSUE THREAD

**Issue by Ryder2048** [MatrixTM/MultiAccountGenerator#26]
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Generator.run() done, defined at .\generator.py:131> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File ".\generator.py", line 173, in <module>
    run(Generator().run())
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\runners.py", line 46, in run
    _cancel_all_tasks(loop)
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\runners.py", line 61, in _cancel_all_tasks
    loop.run_until_complete(
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 595, in run_until_complete
    self.run_forever()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 563, in run_forever
    self._run_once()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1844, in _run_once
    handle._run()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File ".\generator.py", line 152, in run
    await gather(*self.tasks)
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 595, in run_until_complete
    self.run_forever()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 563, in run_forever
    self._run_once()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1844, in _run_once
    handle._run()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File ".\generator.py", line 159, in generate
    request = await session.post(choice(url), data={"gen": ""},
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1042, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1060, in _create_connection_transport
    protocol = protocol_factory()
  File "C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\typing.py", line 870, in __new__
    obj = super().__new__(cls)
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<Generator.generate() running at .\generator.py:166> cb=[gather.<locals>._done_callback() at C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py:751, gather.<locals>._done_callback() at C:\Users\ujinj\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py:751]>

![image](https://user-images.githubusercontent.com/94588756/227532685-94546416-45ca-41aa-90f2-67d520ebcdc2.png)

**Comment by BlacKSnowDot0** [comment]
fixed
